City.create!(name: 'San Francisco')
City.create!(name: 'Seattle')
City.create!(name: 'Austin')
City.create!(name: 'Toronto')
City.create!(name: 'New York')
City.create!(name: 'Las Vegas')
City.create!(name: 'Boston')